### PR TITLE
Update color_customization_example.md

### PR DESCRIPTION
**Pull request by BdR76**
Added extra step for users new to Visual Studio Code, some won't know where the command palette is

### CODE REVIEW

**Comment by mechatroner** [comment]
Thank you very much! 
I was actually just thinking the other day about how light color themes are less effective for distinguishing different colors (even mentioned this in the readme), but I tried this customization and it works really well. I don't know why I never tried to come up with a decent set of colors for Light color themes (probably because I always use dark themes).

**Comment by mechatroner** [comment]
I also just mentioned the customization in the readme and also added a link to Notepad++ CSVLint. I am really happy to see that more and more editors have similar plugins now!

**Comment by BdR76** [comment]
Thanks for linking to the CSV Lint plug-in. And btw I used [this script](https://github.com/BdR76/CSVLint/tree/master/extra#generate_colorspy) to get a 10 colors sequence with the most contrast between each color.

As for the light color theme, in the CSV Lint plug-in it uses the background colors, which works quite well I think. Does the `tokenColorCustomizations` in Visual Studio Code have any option to change the background color per token? It didn't show up in the autocomplete when editing the JSON settings.

**Comment by mechatroner** [comment]
Thanks for linking the script, it is a really cool idea to use HSV circle to find a set of the most contrasting colors! When I needed to do something similar, I just used a trial-and-error approach which obviously produced a non-optimal result. 
There is also a theory that people better distinguish colors that they can name: https://eagereyes.org/blog/2011/you-only-see-colors-you-can-name so another approach to try could be to start with a set of well-known colors (although this list is probably culturally dependent) and add remaining colors based on maximum distance from the well-known ones. 

Regarding using "background" color customization -  it is available per the schema, but the value has no effect: https://github.com/microsoft/vscode/issues/3429 
There are actually 3 ways to do highlighting in VSCode: syntax files, semantic tokenization, and editor decorations, and it looks like the third method does allow setting background highlighting (https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions), but Rainbow CSV currently only uses the first 2 methods only. I might explore this later, thanks for the idea!

**Pull request merged**
