### PR TITLE
Add SetHeaderLine command

### PR DESCRIPTION
**Pull request by WetDesertRock**
This adds a SetHeaderLine that will use the currently selected line as a header. This allows the user to easily work around issues posed in #13 and #14. This is also added to the editor context menu to allow users to right click.

### CODE REVIEW

**Review by mechatroner — CHANGES_REQUESTED** [review]
Hi @WetDesertRock!

I think the real reason why Rainbow CSV needs SetHeaderLine function that you propose is that the current SetVirtualHeader command provides very poor UI/UX.
Basically, I would prefer to have SetVirtualHeader work like a mix between its current implementation where the user can edit the header line and SetHeaderLine.
What will change in SetVirtualHeader:
1. The current line will be provided as the default in the input box like you suggest (instead of taking the first non-comment line like in the current implementation)
2. The current file separator will be used to split the virtual header line from the input box (instead of always using comma like in the current implementation)

This slightly changes the current behavior so we will have to update the documentation both in the README file and the input box explanation message.
Maybe it's worth to try to use window.createInputBox instead of window.showInputBox to emphasize the change in the logic which will be quite significant for non-comma separated files.
BTW if window.createInputBox supports multiple buttons we can have a UI like this:

"Use the header line under the cursor: <line under the cursor sampled from the file>" -> confirm_button_1 
"Or enter your own custom header line" -> input text field -> confirm_button_2

So please, instead of creating the new command just go ahead and update the existing SetVirtualHeader command to use the current line by default as in SetHeaderLine.
I think that having 2 commands with very similar purposes would be confusing.

If you want you can also try to do the createInputBox part, but if not I will experiment with this later myself before publishing the next release.

**Comment by WetDesertRock** [comment]
Hi @mechatroner I'd actually disagree with the assessment that we would want one command to encapsulate all possible behavior. At work I use this plugin all of the time on many different CSV files throughout the day. There are frequently are lines in the file before the header or data that confuse this plugin. Having a context menu item to set the current header line would be a large improvement over having to jump into a dialog box just to skip through it. Additionally I don't believe having one command to set the selected line as the header, and one to edit the header manually would be very confusing for the end user. Perhaps I should change the command's text to be "Use selected line as header" to make the behavior more clear.

That being said I do see what you say about the SetVirtualHeader implementation being confusing and agree with your proposed changes. If there are two commands perhaps the SetVirtualHeader should still by default populate with the current header. So if you wanted a different line and then tweak it you could right click, set current line as header, then set virtual header.

After reading your comment I realized there is a bug with my implementation that will prevent it from working on non-csv files properly. I believe I can fix this and the weird "SetVirtualHeader always being comma separated" issue by updating [extension.js:264](https://github.com/mechatroner/vscode_rainbow_csv/blob/master/extension.js#L264) to use "delim" instead of hardcoding the comma To do this the SetVirtualHeader function would need some minor tweaking in order to still function well.

**Comment by mechatroner** [comment]
I see, your main objection is that having to skip through the dialog could be annoying, I think this a reasonable objection. OK let's have two commands then. Just fix the bug, please, and I will merge your pull request.

If you want you can also refactor the code to use JSON.stringify(header_array) and save it to the global state but under a different key.

**Comment by WetDesertRock** [comment]
I somewhat started writing code and forgot half of what you said. I switched over to using JSON.stringify but used the same key. I included code in get_header for compatibility. Theoretically users shouldn't notice a difference.

**Comment by mechatroner** [comment]
I think this is great! Thank you very much for your contribution, @WetDesertRock !
BTW since we have 2-header related commands, I am thinking about maybe adding a third one: SetVirtualColumnName - which will allow setting the column name just for the column under the cursor.

And there are enough features to make a new release now, so I will start working on it within a week or two, so the next version of Rainbow CSV should be available within a month. I will post an update when it is ready.

**Comment by mechatroner** [comment]
@WetDesertRock I just published version 1.8.0 which includes the new "SetHeaderLine" command

**Pull request merged**
